import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider
          appearance={{
            // choose a base (optional)
            variables: {
              colorText: "var(--institute-blue)",
            },
            elements: {
              formButtonPrimary:
                "!bg-[rgb(var(--institute-blue))] text-primary-foreground hover:bg-primary/90 h-11 rounded-lg",
              formFieldInput:
                "bg-white dark:bg-neutral-900 border-neutral-300 dark:border-neutral-700 focus:ring-2 focus:ring-primary/40",
              socialButtonsBlockButton:
                "border-2 border-primary text-primary hover:bg-primary/5",
            },
          }}
        >
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
